# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
                model_name='voyuser',
                name='avatar'
        ),
        migrations.AddField(
            model_name='voyuser',
            name='avatar',
            field=models.IntegerField(choices=[(1, '/media/users/avatars/1.png'), (2, '/media/users/avatars/2.png'), (3, '/media/users/avatars/3.png'), (4, '/media/users/avatars/4.png'), (5, '/media/users/avatars/5.png'), (6, '/media/users/avatars/6.png'), (7, '/media/users/avatars/7.png'), (8, '/media/users/avatars/8.png'), (9, '/media/users/avatars/9.png'), (10, '/media/users/avatars/10.png'), (11, '/media/users/avatars/11.png'), (12, '/media/users/avatars/12.png'), (13, '/media/users/avatars/13.png'), (14, '/media/users/avatars/14.png'), (15, '/media/users/avatars/15.png'), (16, '/media/users/avatars/16.png'), (17, '/media/users/avatars/17.png'), (18, '/media/users/avatars/18.png'), (19, '/media/users/avatars/19.png'), (20, '/media/users/avatars/20.png'), (21, '/media/users/avatars/21.png'), (22, '/media/users/avatars/22.png'), (23, '/media/users/avatars/23.png')], default=1),
        ),
    ]
