# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('user.voyuser',),
        ),
        migrations.CreateModel(
            name='GlobalUserAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('user.voyuser',),
        ),
        migrations.CreateModel(
            name='LocalUserAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('user.voyuser',),
        ),
        migrations.CreateModel(
            name='MapperUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('user.voyuser',),
        ),
    ]
