# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_adminuser_globaluseradmin_localuseradmin_mapperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_voyuser_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voyuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voyuser',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_voyuser_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voyuser',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
