# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_voyuser_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapperuser',
            options={'ordering': ('first_name', 'username')},
        ),
    ]
