# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20171130_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyuser',
            name='avatar',
            field=models.IntegerField(choices=[(1, '/media/users/avatars/group-1.png'), (2, '/media/users/avatars/group-2.png'), (3, '/media/users/avatars/group-3.png'), (4, '/media/users/avatars/group-4.png'), (5, '/media/users/avatars/group-5.png'), (6, '/media/users/avatars/group-6.png'), (7, '/media/users/avatars/group-7.png'), (8, '/media/users/avatars/group-8.png'), (9, '/media/users/avatars/group-9.png'), (10, '/media/users/avatars/group-10.png'), (11, '/media/users/avatars/group-11.png'), (12, '/media/users/avatars/group-12.png'), (13, '/media/users/avatars/group-13.png'), (14, '/media/users/avatars/group-14.png'), (15, '/media/users/avatars/group-15.png'), (16, '/media/users/avatars/group-16.png'), (17, '/media/users/avatars/group-17.png'), (18, '/media/users/avatars/group-18.png'), (19, '/media/users/avatars/group-19.png'), (20, '/media/users/avatars/group-20.png'), (21, '/media/users/avatars/group-21.png'), (22, '/media/users/avatars/group-22.png'), (23, '/media/users/avatars/group-23.png'), (24, '/media/users/avatars/group-24.png'), (25, '/media/users/avatars/group-25.png')], default=1),
        ),
    ]
