# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180426_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyuser',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voyuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voyuser',
            name='tell_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
