# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ('language',)},
        ),
    ]
