# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import voicesofyouth.report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('can_receive_comments', models.BooleanField(default=True, verbose_name='Can receive comments')),
                ('editable', models.BooleanField(default=True, verbose_name='Editable')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Rejected')], default=2, verbose_name='Status')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'default_objects',
            },
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('text', models.TextField(verbose_name='Comment')),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Rejected')], default=2, verbose_name='Status')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reports Comments',
                'verbose_name_plural': 'Reports Comments',
                'db_table': 'report_reports_comments',
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(blank=True, upload_to=voicesofyouth.report.models.get_content_file_path, verbose_name='File')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Report file',
                'verbose_name_plural': 'Reports files',
                'db_table': 'report_report_files',
            },
        ),
        migrations.CreateModel(
            name='ReportURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Report URL',
                'verbose_name_plural': "Reports URL's",
                'db_table': 'report_report_url',
            },
        ),
    ]
