# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
        ('tag', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporturl',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reporturl_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporturl',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reporturl_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporturl',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='report.Report'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reportfile_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reportfile_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='report.Report'),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reportcomment_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reportcomment_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='report.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_report_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_report_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tag.Tag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='report',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='theme.Theme'),
        ),
    ]
