# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import voicesofyouth.report.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_auto_20171026_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('media_type', models.CharField(choices=[('link', 'Link'), ('image', 'Image'), ('video', 'Video')], max_length=5, verbose_name='Type')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, upload_to=voicesofyouth.report.models.get_content_file_path, verbose_name='File')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reportmedia_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reportmedia_modifications', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_medias', to='report.Report')),
            ],
            options={
                'verbose_name': 'Report Media',
                'verbose_name_plural': 'Reports Medias',
                'db_table': 'report_report_medias',
            },
        ),
        migrations.RemoveField(
            model_name='reportmedias',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportmedias',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='reportmedias',
            name='report',
        ),
        migrations.DeleteModel(
            name='ReportMedias',
        ),
    ]
