# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20171103_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcomment',
            name='creation_timestamp',
        ),
    ]
