# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 20:08
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_reportcomment_creation_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
