# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20171026_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='can_receive_comment',
            new_name='can_receive_comments',
        ),
    ]
