# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20171110_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelManagers(
            name='report',
            managers=[
            ],
        ),
    ]
