# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20171130_1928'),
        ('report', '0005_auto_20171128_1838'),
    ]

    operations = [
    ]
