# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_merge_20171130_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='File'),
        ),
    ]
