# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20180111_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, upload_to='reports', verbose_name='File'),
        ),
    ]
