# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_report_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmedia',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
