# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import voicesofyouth.report.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0008_auto_20171027_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(blank=True, upload_to=voicesofyouth.report.models.get_content_file_path, verbose_name='File')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5, verbose_name='Type')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reportfile_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reportfile_modifications', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='report.Report')),
            ],
            options={
                'verbose_name': 'Report file',
                'verbose_name_plural': 'Reports files',
                'db_table': 'report_report_files',
            },
        ),
        migrations.CreateModel(
            name='ReportURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reporturl_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reporturl_modifications', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='report.Report')),
            ],
            options={
                'verbose_name': 'Report URL',
                'verbose_name_plural': "Reports URL's",
                'db_table': 'report_report_url',
            },
        ),
        migrations.RemoveField(
            model_name='reportmedia',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportmedia',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='reportmedia',
            name='report',
        ),
        migrations.DeleteModel(
            name='ReportMedia',
        ),
    ]
