# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import voicesofyouth.report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20180111_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, upload_to=voicesofyouth.report.models.get_content_file_path, verbose_name='File'),
        ),
    ]
