# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20171027_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reportcomment',
            name='author',
        ),
    ]
