# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0009_auto_20180111_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Revaluation'), (3, 'Not Approved')], verbose_name='Status')),
                ('origin', models.IntegerField(choices=[(1, 'Report'), (2, 'Comment')], verbose_name='Origin')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('read', models.BooleanField(default=False, verbose_name='Readed')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reportnotification_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='report_reportnotification_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Notifications',
                'verbose_name_plural': 'Reports Notifications',
                'db_table': 'report_report_notification',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Not Approved')], default=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Not Approved')], default=2, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='reportnotification',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='report.Report'),
        ),
    ]
