# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20180123_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportnotification',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Not Approved'), (4, 'Revaluation')], verbose_name='Status'),
        ),
    ]
