# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_reportfile_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfile',
            old_name='thumb',
            new_name='thumbnail',
        ),
    ]
