# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20180223_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfile',
            old_name='thumbnail',
            new_name='_thumbnail',
        ),
    ]
