# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20180403_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfile',
            old_name='thumbnail',
            new_name='_thumbnail',
        ),
    ]
