# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20180410_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
