# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='tag_tag_creations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting'),
        ),
        migrations.AddField(
            model_name='tag',
            name='modified_by',
            field=models.ForeignKey(default=1, help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='tag_tag_modifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='modified_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified'),
        ),
    ]
