# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20171020_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='modified_on',
        ),
    ]
