# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import voicesofyouth.translation.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', voicesofyouth.translation.fields.CharFieldTranslatable(max_length=256, verbose_name='Name')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('description', voicesofyouth.translation.fields.TextFieldTranslatable(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
