# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20171026_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='project.Project'),
        ),
    ]
