# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20171023_2106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='themetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='themetranslation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='themetranslation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='themetranslation',
            name='theme',
        ),
        migrations.DeleteModel(
            name='ThemeTranslation',
        ),
    ]
