# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20171110_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
