# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 12:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20171121_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='bounds',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, srid=4326),
        ),
    ]
