# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:40
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20171020_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tag.Tag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
