# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_auto_20171020_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='theme_theme_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theme',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='theme_theme_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='themetranslation',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='theme_themetranslation_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='themetranslation',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='theme_themetranslation_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='themetranslation',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='theme.Theme'),
        ),
    ]
