# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_auto_20180109_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='allow_links',
            field=models.BooleanField(default=True, verbose_name='Allow mappers to add links to reports'),
        ),
    ]
