# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_auto_20171020_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themetranslation',
            options={'ordering': ('language',), 'verbose_name': 'Themes Translation', 'verbose_name_plural': 'Themes Translations'},
        ),
    ]
