# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_auto_20180426_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='theme_theme_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theme',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='theme_theme_modifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
