# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171023_1317'),
        ('theme', '0007_auto_20171023_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={},
        ),
        migrations.AlterModelManagers(
            name='theme',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together=set([('project', 'name')]),
        ),
    ]
