# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_auto_20171023_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='themetranslation',
            unique_together=set([('theme', 'language')]),
        ),
    ]
