# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_themefavoriteby_themetags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themefavoriteby',
            options={'verbose_name': 'Themes Favorite By', 'verbose_name_plural': 'Themes Favorite By'},
        ),
        migrations.AlterModelOptions(
            name='themelanguage',
            options={'verbose_name': 'Themes Languages', 'verbose_name_plural': 'Themes Languages'},
        ),
        migrations.AlterModelOptions(
            name='themetags',
            options={'verbose_name': 'Themes Tags', 'verbose_name_plural': 'Themes Tags'},
        ),
        migrations.AlterModelTable(
            name='themefavoriteby',
            table='themes_theme_favorite_by',
        ),
        migrations.AlterModelTable(
            name='themelanguage',
            table='themes_theme_languages',
        ),
        migrations.AlterModelTable(
            name='themetags',
            table='themes_theme_tags',
        ),
    ]
