# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_auto_20170904_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='enabled',
        ),
    ]
