# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_remove_theme_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'default_manager_name': 'default_objects'},
        ),
        migrations.AlterModelManagers(
            name='theme',
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='themelanguage',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_set', to='themes.Theme'),
        ),
    ]
