# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_auto_20170908_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themelanguage',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_language', to='themes.Theme'),
        ),
    ]
