# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0008_auto_20170908_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_themes', to='maps.Map'),
        ),
    ]
