# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0009_auto_20170908_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themetags',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_tags', to='themes.Theme'),
        ),
    ]
