# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170914_1757'),
        ('themes', '0010_auto_20170911_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='mappers',
            field=models.ManyToManyField(to='projects.ProjectUsers'),
        ),
    ]
