# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20170831_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='system_tag',
            field=models.BooleanField(default=False, verbose_name='System Tag'),
        ),
    ]
