# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20170906_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'default_manager_name': 'default_objects'},
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project'),
        ),
    ]
