# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20170908_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='system_tag',
        ),
    ]
