version: '3.3'

services:
  voy-database:
      image: eltonplima/voy-db-dev:latest
      build:
        context: .
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=development
      command: -c fsync=off
  pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=dba@unicef.com
        - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      ports:
        - 8080:80
  voy-app:
    image: eltonplima/voy-app:latest
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
