version: '3.3'

services:
  voy_database:
      image: mdillon/postgis
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=${POSTGRES_USER:-voy}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-development}
        - POSTGRES_DB=${POSTGRES_DB:-voydev}
  pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=dba@unicef.com
        - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      ports:
        - 9000:80
  voy_dashboard:
    image: unicef/voy_dashboard:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - voy_database
    ports:
      - 8000:8000
    environment:
      - DEBUG=${DEBUG:-True}
      - DATABASE_URL=postgis://voy:development@voy_database/voydev
      - ALLOWED_HOSTS=*
      - CORS_ORIGIN_ALLOW_ALL=${CORS_ORIGIN_ALLOW_ALL:-True}
      - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so.20
  voy_frontend:
    image: unicef/voy_frontend:latest
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      args:
        BACKEND_SERVER: http://0.0.0.0:8000
    depends_on:
      - voy_dashboard
    ports:
      - 7000:80
