# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 17:42
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('tag', '0001_initial'),
        ('project', '0002_auto_20171103_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tag.Tag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
