# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20171020_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='project_project_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='project_project_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectregion',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='project_projectregion_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectregion',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='project_projectregion_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='project_projecttranslation_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='project_projecttranslation_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='project',
            table='project_projects',
        ),
    ]
