# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171023_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttranslation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projecttranslation',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='ProjectTranslation',
        ),
    ]
