# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20171110_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='boundary',
            new_name='bounds',
        ),
    ]
