# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20171122_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
