# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 10:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bounds',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
