# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import voicesofyouth.project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180315_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=voicesofyouth.project.models.upload_to),
        ),
    ]
