# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:54
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group

from ..models import PROTECTED_GROUPS


def create_protected_groups(apps, schema_editor):
    groups = [Group(name=group) for group in PROTECTED_GROUPS]
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).bulk_create(groups)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_protected_groups),
    ]
