# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('themes', '0001_initial'),
        ('projects', '0002_auto_20171006_1929'),
        ('maps', '0002_auto_20171006_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttags',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reporttags_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttags',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reporttags_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttags',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tags', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='reporttags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tags_tag', to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='reportmedias',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reportmedias_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportmedias',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reportmedias_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportmedias',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_medias', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='reportlanguage',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reportlanguage_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportlanguage',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reportlanguage_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportlanguage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_languages', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='reportfavoriteby',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reportfavoriteby_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportfavoriteby',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reportfavoriteby_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportfavoriteby',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
        migrations.AddField(
            model_name='reportcomments',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reportcomments_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomments',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reportcomments_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomments',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_report_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_reports', to='maps.Map'),
        ),
        migrations.AddField(
            model_name='report',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_report_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='report',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_reports', to='themes.Theme'),
        ),
    ]
