# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='share_facebook',
        ),
        migrations.RemoveField(
            model_name='report',
            name='share_twitter',
        ),
        migrations.AddField(
            model_name='report',
            name='comments',
            field=models.BooleanField(default=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='report',
            name='sharing',
            field=models.BooleanField(default=True, verbose_name='Sharing'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Rejected')], default=2, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='reportcomments',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Rejected')], default=2, verbose_name='Status'),
        ),
    ]
