# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170901_1344'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportcomments',
            table='reports_report_comments',
        ),
        migrations.AlterModelTable(
            name='reportfavoriteby',
            table='reports_report_favorite_by',
        ),
        migrations.AlterModelTable(
            name='reportlanguage',
            table='reports_report_languages',
        ),
        migrations.AlterModelTable(
            name='reporttags',
            table='reports_report_tags',
        ),
    ]
