# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20170908_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_reports', to='maps.Map'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_reports', to='themes.Theme'),
        ),
    ]
