# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import voicesofyouth.reports.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0008_auto_20170911_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMedias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('media_type', models.CharField(choices=[('link', 'Link'), ('image', 'Image'), ('video', 'Video')], max_length=5, verbose_name='Type')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, upload_to=voicesofyouth.reports.models.get_content_file_path, verbose_name='File')),
                ('screenshot', models.FileField(blank=True, upload_to=voicesofyouth.reports.models.get_content_file_path, verbose_name='Screenshot')),
                ('extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Extra')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Francais'), ('sq', 'Shqip'), ('tr', 'Turkce'), ('ar', 'Arabic')], default='en', max_length=90)),
                ('visibled', models.BooleanField(default=True, verbose_name='Visibled')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reportmedias_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_reportmedias_modifications', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_medias', to='reports.Report')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'default_objects',
            },
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
