# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reportmedias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportmedias',
            options={'verbose_name': 'Reports Medias', 'verbose_name_plural': 'Reports Medias'},
        ),
        migrations.AlterModelManagers(
            name='reportmedias',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='reportmedias',
            table='reports_report_medias',
        ),
    ]
