# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20170912_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcomments',
            name='project',
        ),
        migrations.AlterField(
            model_name='reportcomments',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='reports.Report'),
        ),
    ]
