# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20170913_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttags',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
        migrations.AlterField(
            model_name='reporttags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tags', to='tags.Tag'),
        ),
    ]
