# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20170914_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttags',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tags', to='reports.Report'),
        ),
        migrations.AlterField(
            model_name='reporttags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tags_tag', to='tags.Tag'),
        ),
    ]
