export const SET_HEADER_CONFIG = 'SET_HEADER_CONFIG';

export const SET_PROJECTS_LIST = 'SET_PROJECTS_LIST';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE';
export const SET_DISCLAIMER_PROJECT = 'SET_DISCLAIMER_PROJECT';

export const SIDEBAR_SET_CONFIGS = 'SIDEBAR_SET_CONFIGS';
export const SET_THEMES = 'SET_THEMES';
export const SET_CURRENT_THEME = 'SET_CURRENT_THEME';
export const SET_LAST_REPORTS = 'SET_LAST_REPORTS';

export const SET_REPORTS = 'SET_REPORTS';
export const SET_CURRENT_REPORT = 'SET_CURRENT_REPORT';
export const ADD_REPORTS_LIST = 'ADD_REPORTS_LIST';
export const REMOVE_REPORTS_LIST = 'REMOVE_REPORTS_LIST';
export const SET_REPORT_COMMENTS = 'SET_REPORT_COMMENTS';
export const SET_REPORT_MEDIAS = 'SET_REPORT_MEDIAS';
export const CLEAR_REPORTS_LIST = 'CLEAR_REPORTS_LIST';
