export const SET_HEADER_CONFIG = 'SET_HEADER_CONFIG';

export const SET_PROJECTS_LIST = 'SET_PROJECTS_LIST';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const SET_DISCLAIMER_PROJECT = 'SET_DISCLAIMER_PROJECT';

export const SIDEBAR_SET_CONFIGS = 'SIDEBAR_SET_CONFIGS';
export const SIDEBAR_SET_CURRENT_TAB = 'SIDEBAR_SET_CURRENT_TAB';
export const SET_THEMES = 'SET_THEMES';
export const SET_CURRENT_THEME = 'SET_CURRENT_THEME';
