export const SET_HEADER_CONFIG = 'SET_HEADER_CONFIG';

export const SET_PROJECTS_LIST = 'SET_PROJECTS_LIST';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const SET_DISCLAIMER_PROJECT = 'SET_DISCLAIMER_PROJECT';
