# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyhome', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
