# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyhome', '0004_slide_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('order',), 'verbose_name': 'Home Slide', 'verbose_name_plural': 'Home Slide'},
        ),
    ]
