# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voyhome', '0005_auto_20180528_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='accepted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
