# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyhome', '0006_auto_20180619_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='voyhome_about_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='about',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='voyhome_about_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='voyhome_contact_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='voyhome_contact_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slide',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='voyhome_slide_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slide',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='voyhome_slide_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
