# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import voicesofyouth.medias.models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='mime_type',
        ),
        migrations.AddField(
            model_name='media',
            name='extra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Extra'),
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, upload_to=voicesofyouth.medias.models.get_content_file_path, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='media',
            name='screenshot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
