# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import voicesofyouth.medias.models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_auto_20170831_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='screenshot',
            field=models.FileField(blank=True, upload_to=voicesofyouth.medias.models.get_content_file_path, verbose_name='Screenshot'),
        ),
    ]
