# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_auto_20170831_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('link', 'Link'), ('audio', 'Audio'), ('video', 'Video')], max_length=5, verbose_name='Type'),
        ),
    ]
