# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_auto_20170831_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('link', 'Link'), ('image', 'Image'), ('video', 'Video')], max_length=5, verbose_name='Type'),
        ),
    ]
