# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusers',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectusers_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectusers',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectusers_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectusers',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='projectusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projecttranslation_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projecttranslation_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectregion',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectregion_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectregion',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectregion_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectregion',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_project_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_project_modifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
