# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranslation',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projecttranslation_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projecttranslation_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectregion',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectregion_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectregion',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectregion_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectregion',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_region', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_project_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='local_admin_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_local_admin', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_project_modifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
