# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170831_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
