# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='window_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Window Title'),
        ),
    ]
