# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170831_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='settinglanguage',
            options={'verbose_name': 'Settings Languages', 'verbose_name_plural': 'Settings Languages'},
        ),
    ]
