# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170831_1829'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settinglanguage',
            table='projects_setting_languages',
        ),
    ]
