# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_window_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsettinglanguage',
            old_name='title',
            new_name='name',
        ),
    ]
