# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171009_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlanguage',
            options={'verbose_name': 'Project Languages', 'verbose_name_plural': 'Projects Languages'},
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
