# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170914_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectusers',
            options={'verbose_name': 'Projects Users', 'verbose_name_plural': 'Projects Users'},
        ),
        migrations.AddField(
            model_name='projectusers',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Local Administrator'), (2, 'Mapper')], default=None, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='projectusers',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='projects.Project'),
        ),
    ]
