# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20170914_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectusers',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Local Administrator'), (2, 'Mapper')], verbose_name='Type'),
        ),
    ]
