# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20171006_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
    ]
