# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 16:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_auto_20171006_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectsetting_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectsetting_modifications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.RemoveField(
            model_name='setting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='project',
        ),
        migrations.AlterField(
            model_name='settinglanguage',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectSetting'),
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
