# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20171006_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsetting',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
