# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='location',
            new_name='bounds',
        ),
    ]
