# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20170904_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapadmin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='mapadmin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mapadmin',
            name='map',
        ),
        migrations.RemoveField(
            model_name='mapadmin',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='MapAdmin',
        ),
    ]
