# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20170904_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='enabled',
        ),
    ]
